# Base component API configuration
__merge__: ../../api/comp_method.yaml

# Component configuration
name: "pca"
label: "PCA"
summary: A linear method that finds orthogonal directions to compute the two-dimensional embedding.
description: |
  Principal Component Analysis is a linear method that finds orthogonal
  directions in the data that capture the most variance. The first two
  principal components are chosen as the two-dimensional embedding. We select
  only the first two principal components as the two-dimensional embedding. PCA
  is calculated on the logCPM expression matrix with and without selecting 1000
  HVGs.
references:
  doi: 10.1080/14786440109462720
links:
  repository: https://github.com/scverse/scanpy
  documentation: https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.pca.html
info:
  preferred_normalization: log_cp10k
  variants:
    pca_logCP10k:
    pca_logCP10k_1kHVG:
      n_hvg: 1000

# Script configuration
arguments:
  - name: "--n_hvg"
    type: integer
    description: Number of highly variable genes to subset to. If not specified, the input matrix will not be subset.
resources:
  - type: python_script
    path: script.py

# Platform configuration
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages: scanpy
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, highmem, highcpu]
