# Base component API configuration
__merge__: ../../api/comp_metric.yaml

# Component configuration
name: "density_preservation"
info:
  metrics:
    - name: density_preservation
      label: Density preservation
      summary: "Similarity between local densities in the high-dimensional data and the reduced data."
      description: |
        "Similarity between local densities in the high-dimensional data and the reduced data.
        This is computed as the pearson correlation of local radii with the local radii in the original data space."
      references:
        doi: 10.1038/s41587-020-00801-7
      min: -1
      max: 1
      maximize: true

# Script configuration
arguments:
  - name: "--n_neighbors"
    type: integer
    default: 30
    description: "Number of neighbors to use for density estimation."
  - name: "--seed"
    type: integer
    default: 42
    description: "Random seed."
resources:
  - type: python_script
    path: script.py

# Platform configuration
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages:
          - umap-learn
          - pynndescent~=0.5.11 # See https://github.com/openproblems-bio/openproblems-v2/issues/266
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, lowmem, midcpu]
