# Base component API configuration
__merge__: ../../api/comp_method.yaml

# Component configuration
name: "densmap"
label: densMAP
summary: "Modified UMAP with preservation of local density information"
description: "A modification of UMAP that adds an extra cost term in order to preserve information about the relative local density of the data. It is performed on the same inputs as UMAP."
references:
  doi: 10.1038/s41587-020-00801-7
links:
  repository: https://github.com/lmcinnes/umap
  documentation: https://umap-learn.readthedocs.io/en/latest/densmap_demo.html
info:
  preferred_normalization: log_cp10k
  variants:
    densmap_logCP10k:
    densmap_pca_logCP10k:
      n_pca_dims: 50
    densmap_logCP10k_1kHVG:
      n_hvg: 1000
    densmap_pca_logCP10k_1kHVG:
      n_pca_dims: 50
      n_hvg: 1000

# Script configuration
arguments:
  - name: "--n_hvg"
    type: integer
    description: Number of highly variable genes to subset to. If not specified, the input matrix will not be subset.
  - name: "--n_pca_dims"
    type: integer
    description: Number of PCA dimensions to use. If not specified, no PCA will be performed.
resources:
  - type: python_script
    path: script.py

# Platform configuration
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages:
          - umap-learn
          - pynndescent~=0.5.11 # See https://github.com/openproblems-bio/openproblems-v2/issues/266
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, highmem, highcpu]
