name: "true_features"
namespace: "control_methods"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input"
    label: "Dataset"
    summary: "The dataset to pass to a method."
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized expression values"
          required: true
        var:
        - type: "double"
          name: "hvg_score"
          description: "High variability gene score (normalized dispersion). The greater,\
            \ the more variable."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/task_dimensionality_reduction/cxg_mouse_pancreas_atlas/dataset.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input_solution"
    label: "Test data"
    summary: "The data for evaluating a dimensionality reduction."
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized expression values"
          required: true
        obs:
        - type: "string"
          name: "cell_type"
          description: "Classification of the cell type based on its characteristics\
            \ and function within the tissue or organism."
          required: true
        var:
        - type: "double"
          name: "hvg_score"
          description: "High variability gene score (normalized dispersion). The greater,\
            \ the more variable."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - name: "dataset_name"
          type: "string"
          description: "Nicely formatted name."
          required: true
        - type: "string"
          name: "dataset_url"
          description: "Link to the original source of the dataset."
          required: false
        - name: "dataset_reference"
          type: "string"
          description: "Bibtex reference of the paper in which the dataset was published."
          required: false
        - name: "dataset_summary"
          type: "string"
          description: "Short description of the dataset."
          required: true
        - name: "dataset_description"
          type: "string"
          description: "Long description of the dataset."
          required: true
        - name: "dataset_organism"
          type: "string"
          description: "The organism of the sample in the dataset."
          required: false
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/task_dimensionality_reduction/cxg_mouse_pancreas_atlas/solution.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    label: "Embedding"
    summary: "A dataset with dimensionality reduction embedding."
    info:
      format:
        type: "h5ad"
        obsm:
        - type: "double"
          name: "X_emb"
          description: "The dimensionally reduced embedding."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/task_dimensionality_reduction/cxg_mouse_pancreas_atlas/embedding.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
label: "True Features"
summary: "Positive control by retaining the dimensionality without loss of information."
description: "This serves as a positive control since the original high-dimensional\
  \ data is retained as is, without any loss of information"
test_resources:
- type: "file"
  path: "resources_test/task_dimensionality_reduction/cxg_mouse_pancreas_atlas/"
  dest: "resources_test/task_dimensionality_reduction/cxg_mouse_pancreas_atlas/"
- type: "python_script"
  path: "check_config.py"
  is_executable: true
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
info:
  preferred_normalization: "log_cp10k"
  type: "control_method"
  type_info:
    label: "Control method"
    summary: "Quality control methods for verifying the pipeline."
    description: "Control methods have the same interface as the regular methods\n\
      but also receive the solution object as input. It serves as a\nstarting point\
      \ to test the relative accuracy of new methods in\nthe task, and also as a quality\
      \ control for the metrics defined\nin the task.\n"
status: "enabled"
repositories:
- type: "github"
  name: "core"
  repo: "openproblems-bio/core"
  tag: "build/main"
  path: "viash/core"
license: "MIT"
links:
  repository: "https://github.com/openproblems-bio/task_dimensionality_reduction"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "openproblems/base_python:1.0.0"
  namespace_separator: "/"
  entrypoint: []
  cmd: null
build_info:
  config: "src/control_methods/true_features/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/control_methods/true_features"
  executable: "target/nextflow/control_methods/true_features/main.nf"
  viash_version: "0.9.0"
  git_commit: "c3221528561c355858ce68b7fc0c63d9dd59652c"
  git_remote: "https://github.com/openproblems-bio/task_dimensionality_reduction"
package_config:
  name: "task_dimensionality_reduction"
  version: "build_main"
  label: "Dimensionality Reduction for Visualization"
  summary: "Reduction of high-dimensional datasets to 2D for visualization & interpretation."
  description: "Data visualisation is an important part of all stages of single-cell\
    \ analysis, from\ninitial quality control to interpretation and presentation of\
    \ final results. For bulk RNA-seq\nstudies, linear dimensionality reduction techniques\
    \ such as PCA and MDS are commonly used\nto visualise the variation between samples.\
    \ While these methods are highly effective they\ncan only be used to show the\
    \ first few components of variation which cannot fully represent\nthe increased\
    \ complexity and number of observations in single-cell datasets. For this reason\n\
    non-linear techniques (most notably t-SNE and UMAP) have become the standard for\
    \ visualising\nsingle-cell studies. These methods attempt to compress a dataset\
    \ into a two-dimensional space\nwhile attempting to capture as much of the variance\
    \ between observations as possible. Many\nmethods for solving this problem now\
    \ exist. In general these methods try to preserve distances,\nwhile some additionally\
    \ consider aspects such as density within the embedded space or conservation\n\
    of continuous trajectories. Despite almost every single-cell study using one of\
    \ these visualisations\nthere has been debate as to whether they can effectively\
    \ capture the variation in single-cell\ndatasets [@chari2023speciousart].\n\n\
    The dimensionality reduction task attempts to quantify the ability of methods\
    \ to embed the\ninformation present in complex single-cell studies into a two-dimensional\
    \ space. Thus, this task\nis specifically designed for dimensionality reduction\
    \ for visualisation and does not consider other\nuses of dimensionality reduction\
    \ in standard single-cell workflows such as improving the\nsignal-to-noise ratio\
    \ (and in fact several of the methods use PCA as a pre-processing step for this\n\
    reason). Unlike most tasks, methods for the dimensionality reduction task must\
    \ accept a matrix\ncontaining expression values normalised to 10,000 counts per\
    \ cell and log transformed (log-10k) and\nproduce a two-dimensional coordinate\
    \ for each cell. Pre-normalised matrices are required to\nenforce consistency\
    \ between the metric evaluation (which generally requires normalised data) and\n\
    the method runs. When these are not consistent, methods that use the same normalisation\
    \ as used in\nthe metric tend to score more highly. For some methods we also evaluate\
    \ the pre-processing\nrecommended by the method.\n"
  info:
    image: "thumbnail.svg"
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/cxg_mouse_pancreas_atlas/"
      dest: "resources_test/common/cxg_mouse_pancreas_atlas/"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/task_dimensionality_reduction/"
      dest: "resources_test/task_dimensionality_reduction"
  repositories:
  - type: "github"
    name: "core"
    repo: "openproblems-bio/core"
    tag: "build/main"
    path: "viash/core"
  viash_version: "0.9.0"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n"
  authors:
  - name: "Luke Zappia"
    roles:
    - "maintainer"
    - "author"
    info:
      github: "lazappi"
      orcid: "0000-0001-7744-8565"
  - name: "Michal Klein"
    roles:
    - "author"
    info:
      github: "michalk8"
  - name: "Scott Gigante"
    roles:
    - "author"
    info:
      github: "scottgigante"
      orcid: "0000-0002-4544-2764"
  - name: "Ben DeMeo"
    roles:
    - "author"
    info:
      github: "bendemeo"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  - name: "Kai Waldrant"
    roles:
    - "contributor"
    info:
      github: "KaiWaldrant"
      orcid: "0009-0003-8555-1361"
  - name: "Sai Nirmayi Yasa"
    roles:
    - "contributor"
    info:
      github: "sainirmayi"
      orcid: "0009-0003-6319-9803"
  - name: "Juan A. Cordero Varela"
    roles:
    - "contributor"
    info:
      github: "jacorvar"
      orcid: "0000-0002-7373-5433"
  keywords:
  - "single-cell"
  - "openproblems"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_dimensionality_reduction"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_dimensionality_reduction/issues"
