# Base component API configuration
__merge__: ../../api/comp_method.yaml

# Component configuration
name: "tsne"
label: t-SNE
summary: "Minimizing Kullback-Leibler divergence by converting similarities into joint probabilities between data points and the low/high dimensional embedding."
description: |
  t-distributed Stochastic Neighbor Embedding converts similarities between
  data points to joint probabilities and tries to minimize the
  Kullback-Leibler divergence between the joint probabilities of the
  low-dimensional embedding and the high-dimensional data. We use the
  implementation in the scanpy package with the MulticoreTSNE backend taking
  the result of PCA on the logCPM expression matrix (with and without HVG
  selection) as input.
references:
  bibtex: |
    @article{JMLR:v9:vandermaaten08a,
      author  = {Laurens van der Maaten and Geoffrey Hinton},
      title   = {Visualizing Data using t-SNE},
      journal = {Journal of Machine Learning Research},
      year    = {2008},
      volume  = {9},
      number  = {86},
      pages   = {2579--2605},
      url     = {http://jmlr.org/papers/v9/vandermaaten08a.html}
    }
links:
  repository: https://github.com/scverse/scanpy
  documentation: https://scanpy.readthedocs.io/en/stable/generated/scanpy.tl.tsne.html
info:
  preferred_normalization: log_cp10k
  variants:
    tsne_logCP10k:
    tsne_logCP10k_1kHVG:
      n_hvg: 1000

# Script configuration
arguments:
  - name: "--n_hvg"
    type: integer
    description: Number of highly variable genes to subset to. If not specified, the input matrix will not be subset.
  - name: "--n_pca_dims"
    type: integer
    description: Number of PCA dimensions to use. If not specified, no PCA will be performed.
    default: 50
resources:
  - type: python_script
    path: script.py

# Platform configuration
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: apt
        packages:
          - cmake
          - gcc
      - type: python
        github:
          - DmitryUlyanov/Multicore-TSNE
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, highmem, highcpu]
