name: "simlr"
namespace: "methods"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input"
    label: "Dataset"
    summary: "The dataset to pass to a method."
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized expression values"
          required: true
        var:
        - type: "double"
          name: "hvg_score"
          description: "High variability gene score (normalized dispersion). The greater,\
            \ the more variable."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/dimensionality_reduction/pancreas/dataset.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    label: "Embedding"
    summary: "A dataset with dimensionality reduction embedding."
    info:
      format:
        type: "h5ad"
        obsm:
        - type: "double"
          name: "X_emb"
          description: "The dimensionally reduced embedding."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/dimensionality_reduction/pancreas/embedding.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--n_dim"
    description: "Number of dimensions."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--n_clusters"
    description: "Number of clusters to be estimated over the input dataset."
    info: null
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--tuning_param"
    description: "Number of dimensions."
    info: null
    default:
    - 10
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--impute"
    description: "Should the input data be transposed?"
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean"
    name: "--normalize"
    description: "Should the input data be normalized?"
    info: null
    default:
    - false
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--cores_ratio"
    description: "Ratio of the number of cores to be used when computing the multi-kernel."
    info: null
    default:
    - 1
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
resources:
- type: "r_script"
  path: "script.R"
  is_executable: true
label: "SIMLR"
summary: "Multikernel-based learning of distance metrics from gene expression data\
  \ for dimension reduction, clustering and visulaization."
description: "Single-cell Interpretation via Multikernel LeaRning (SIMLR) learns\n\
  cell-to-cell similarity measures from single-cell RNA-seq data in using\nGaussian\
  \ kernels with various hyperparameters in order to perform dimension\nreduction,\
  \ clustering and visualization. SIMLR assumes that if C separable\npopulations exist\
  \ among the N cells, then the similarity matrix should have\nan approximate block-diagonal\
  \ structure with C blocks whereby cells have\nlarger similarities to other cells\
  \ within the same subpopulations. Learned\nsimilarity between two cells should be\
  \ small if the Euclidean distance\nbetween them is large. The cell-to-cell similarity\
  \ is computed using an\noptimization framework over an N x N similarity matrix,\
  \ a low-dimensional\nauxilary matrix enforcing low rank constraint on the similarity\
  \ matrix, and\nthe kernel weights. Dimension reduction is achieved by the stochastic\n\
  neighbor embedding methodology with the learned similarities as input.\n"
test_resources:
- type: "file"
  path: "resources_test/dimensionality_reduction/pancreas/"
  dest: "resources_test/dimensionality_reduction/pancreas/"
- type: "python_script"
  path: "check_config.py"
  is_executable: true
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
info:
  preferred_normalization: "log_cp10k"
  type: "method"
  type_info:
    label: "Method"
    summary: "A dimensionality reduction method."
    description: "A dimensionality reduction method to summarise the biological\n\
      information in a dataset in as few dimensions as possible.\n"
status: "enabled"
repositories:
- type: "github"
  name: "openproblems-v2"
  repo: "openproblems-bio/openproblems-v2"
  tag: "main_build"
license: "MIT"
references:
  doi:
  - "10.1038/nmeth.4207"
links:
  repository: "https://github.com/BatzoglouLabSU/SIMLR"
  docker_registry: "ghcr.io"
  documentation: "https://bioconductor.org/packages/SIMLR/"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "openproblems/base_r:1.0.0"
  namespace_separator: "/"
  setup:
  - type: "r"
    bioc:
    - "SIMLR"
    bioc_force_install: false
  entrypoint: []
  cmd: null
build_info:
  config: "src/methods/simlr/config.vsh.yaml"
  runner: "executable"
  engine: "docker"
  output: "target/executable/methods/simlr"
  executable: "target/executable/methods/simlr/simlr"
  viash_version: "0.9.0"
  git_commit: "ab268cc0d6781cee7140a73b3943761104719ad8"
  git_remote: "https://github.com/openproblems-bio/task_dimensionality_reduction"
package_config:
  name: "task_dimensionality_reduction"
  version: "build_main"
  label: "Dimensionality Reduction for Visualization"
  summary: "Reduction of high-dimensional datasets to 2D for visualization & interpretation."
  description: "Data visualisation is an important part of all stages of single-cell\
    \ analysis, from\ninitial quality control to interpretation and presentation of\
    \ final results. For bulk RNA-seq\nstudies, linear dimensionality reduction techniques\
    \ such as PCA and MDS are commonly used\nto visualise the variation between samples.\
    \ While these methods are highly effective they\ncan only be used to show the\
    \ first few components of variation which cannot fully represent\nthe increased\
    \ complexity and number of observations in single-cell datasets. For this reason\n\
    non-linear techniques (most notably t-SNE and UMAP) have become the standard for\
    \ visualising\nsingle-cell studies. These methods attempt to compress a dataset\
    \ into a two-dimensional space\nwhile attempting to capture as much of the variance\
    \ between observations as possible. Many\nmethods for solving this problem now\
    \ exist. In general these methods try to preserve distances,\nwhile some additionally\
    \ consider aspects such as density within the embedded space or conservation\n\
    of continuous trajectories. Despite almost every single-cell study using one of\
    \ these visualisations\nthere has been debate as to whether they can effectively\
    \ capture the variation in single-cell\ndatasets [@chari2023speciousart].\n\n\
    The dimensionality reduction task attempts to quantify the ability of methods\
    \ to embed the\ninformation present in complex single-cell studies into a two-dimensional\
    \ space. Thus, this task\nis specifically designed for dimensionality reduction\
    \ for visualisation and does not consider other\nuses of dimensionality reduction\
    \ in standard single-cell workflows such as improving the\nsignal-to-noise ratio\
    \ (and in fact several of the methods use PCA as a pre-processing step for this\n\
    reason). Unlike most tasks, methods for the dimensionality reduction task must\
    \ accept a matrix\ncontaining expression values normalised to 10,000 counts per\
    \ cell and log transformed (log-10k) and\nproduce a two-dimensional coordinate\
    \ for each cell. Pre-normalised matrices are required to\nenforce consistency\
    \ between the metric evaluation (which generally requires normalised data) and\n\
    the method runs. When these are not consistent, methods that use the same normalisation\
    \ as used in\nthe metric tend to score more highly. For some methods we also evaluate\
    \ the pre-processing\nrecommended by the method.\n"
  info:
    image: "thumbnail.svg"
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/pancreas/"
      dest: "resources_test/common/pancreas/"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/dimensionality_reduction/"
      dest: "resources_test/dimensionality_reduction"
  repositories:
  - type: "github"
    name: "openproblems-v2"
    repo: "openproblems-bio/openproblems-v2"
    tag: "main_build"
  viash_version: "0.9.0"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n"
  authors:
  - name: "Luke Zappia"
    roles:
    - "maintainer"
    - "author"
    info:
      github: "lazappi"
      orcid: "0000-0001-7744-8565"
  - name: "Michal Klein"
    roles:
    - "author"
    info:
      github: "michalk8"
  - name: "Scott Gigante"
    roles:
    - "author"
    info:
      github: "scottgigante"
      orcid: "0000-0002-4544-2764"
  - name: "Ben DeMeo"
    roles:
    - "author"
    info:
      github: "bendemeo"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  - name: "Kai Waldrant"
    roles:
    - "contributor"
    info:
      github: "KaiWaldrant"
      orcid: "0009-0003-8555-1361"
  - name: "Sai Nirmayi Yasa"
    roles:
    - "contributor"
    info:
      github: "sainirmayi"
      orcid: "0009-0003-6319-9803"
  - name: "Juan A. Cordero Varela"
    roles:
    - "contributor"
    info:
      github: "jacorvar"
      orcid: "0000-0002-7373-5433"
  keywords:
  - "single-cell"
  - "openproblems"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  links:
    repository: "https://github.com/openproblems-bio/task_dimensionality_reduction"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_dimensionality_reduction/issues"
