# Base component API configuration
__merge__: ../../api/comp_method.yaml

# Component configuration
name: "neuralee"
label: NeuralEE
summary: "Non-linear method that uses a neural network to preserve pairwise distances between data points in a high-dimensional space."
description: |
  A neural network implementation of elastic embedding. It is a
  non-linear method that preserves pairwise distances between data points.
  NeuralEE uses a neural network to optimize an objective function that
  measures the difference between pairwise distances in the original
  high-dimensional space and the two-dimensional space. It is computed on both
  the recommended input from the package authors of 500 HVGs selected from a
  logged expression matrix (without sequencing depth scaling) and the default
  logCPM matrix with 1000 HVGs.
references:
  doi: 10.3389/fgene.2020.00786
links:
  repository: "https://github.com/HiBearME/NeuralEE"
  documentation: "https://github.com/HiBearME/NeuralEE#readme"
info:
  preferred_normalization: log_cp10k
  variants:
    neuralee_default:
      normalize: true
      n_hvg: 500
    neuralee_logCP10k_1kHVG:
      normalize: false
      n_hvg: 1000

# Script configuration
arguments:
  - name: "--n_iter"
    type: integer
    description: Number of iterations.
  - name: "--n_hvg"
    type: integer
    description: Number of highly variable genes to subset to. If not specified, the input matrix will not be subset.
    default: 1000
  - name: "--normalize"
    type: boolean
    default: false
    description: Whether to perform own normalization
resources:
  - type: python_script
    path: script.py

# Platform configuration
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages:
          - torch
          - "git+https://github.com/michalk8/neuralee@8946abf"
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, highmem, highcpu]
