# Base component API configuration
__merge__: ../../api/comp_control_method.yaml

# Component configuration
name: "true_features"
label: True Features
summary: "Positive control by retaining the dimensionality without loss of information."
description: "This serves as a positive control since the original high-dimensional data is retained as is, without any loss of information"
info:
  preferred_normalization: log_cp10k
  variants:
    true_features:

# Script configuration
resources:
  - type: python_script
    path: script.py

# Platform configuration
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, highmem, highcpu]
